// Interactive credential setup for the standalone Jira MCP install.
//
// Asks for the minimum (email + API token, optional default project), derives
// the rest from the Jira API, verifies before writing, and stores a personal
// .env in the user config dir (see paths.js). Safe to re-run any time.

import { createInterface } from "node:readline";
import { writeFile, readFile, chmod, mkdir } from "node:fs/promises";
import { readFileSync } from "node:fs";
import { spawn } from "node:child_process";
import { configDir, envPath, isWin } from "./paths.js";

// Optional per-distribution defaults (e.g. your company's Atlassian site) live in
// app/defaults.json, which is NOT committed — so this public source stays generic
// while a built zip can still pre-fill the site. See defaults.example.json.
function loadDefaults() {
  try { return JSON.parse(readFileSync(new URL("../defaults.json", import.meta.url), "utf8")); }
  catch { return {}; }
}
const DEFAULT_SITE = loadDefaults().site || "";
const TOKEN_URL = "https://id.atlassian.com/manage-profile/security/api-tokens";

let rl;
const ask = (q, fallback = "") =>
  new Promise((res) => rl.question(q, (a) => res(a.trim() || fallback)));

function askHidden(q) {
  return new Promise((res) => {
    process.stdout.write(q);
    rl.stdoutMuted = true;
    rl._writeToOutput = (s) => { if (!rl.stdoutMuted) rl.output.write(s); };
    rl.question("", (value) => {
      rl.stdoutMuted = false;
      rl.output.write("\n");
      res(value.trim());
    });
  });
}

function openBrowser(url) {
  try {
    const [cmd, args] =
      isWin ? ["cmd", ["/c", "start", "", url]] :
      process.platform === "darwin" ? ["open", [url]] :
      ["xdg-open", [url]];
    spawn(cmd, args, { detached: true, stdio: "ignore" }).unref();
  } catch { /* the URL is printed anyway */ }
}

const basic = (email, token) => "Basic " + Buffer.from(`${email}:${token}`).toString("base64");

export async function resolveCloudId(site) {
  const res = await fetch(`https://${site}/_edge/tenant_info`);
  if (!res.ok) throw new Error(`Couldn't reach https://${site} (${res.status}). Check the site name.`);
  const { cloudId } = await res.json();
  if (!cloudId) throw new Error(`No cloud id returned for ${site}.`);
  return cloudId;
}

// Returns { accountId, displayName } on success, null on an auth failure.
export async function verify(cloudId, email, token) {
  const res = await fetch(`https://api.atlassian.com/ex/jira/${cloudId}/rest/api/3/myself`, {
    headers: { Authorization: basic(email, token), Accept: "application/json" },
  });
  if (res.status === 401 || res.status === 403) return null;
  if (!res.ok) throw new Error(`Jira /myself → ${res.status}: ${await res.text()}`);
  const me = await res.json();
  return { accountId: me.accountId, displayName: me.displayName };
}

export async function projectExists(cloudId, email, token, key) {
  const res = await fetch(`https://api.atlassian.com/ex/jira/${cloudId}/rest/api/3/project/${encodeURIComponent(key)}`, {
    headers: { Authorization: basic(email, token), Accept: "application/json" },
  });
  return res.ok;
}

// Parse the stored .env into a plain object (or {} if none).
export async function readEnv() {
  try {
    const text = await readFile(envPath, "utf8");
    return Object.fromEntries(
      text.split(/\r?\n/)
        .filter((l) => l && !l.trimStart().startsWith("#") && l.includes("="))
        .map((l) => { const i = l.indexOf("="); return [l.slice(0, i).trim(), l.slice(i + 1).trim().replace(/\s+#.*$/, "")]; }),
    );
  } catch { return {}; }
}

// True if the stored credentials still authenticate. Used to skip the wizard on
// an update so nobody has to re-enter their token.
export async function credentialsValid() {
  const e = await readEnv();
  if (!e.JIRA_CLOUD_ID || !e.JIRA_EMAIL || !e.JIRA_API_TOKEN) return null;
  try {
    const me = await verify(e.JIRA_CLOUD_ID, e.JIRA_EMAIL, e.JIRA_API_TOKEN);
    return me ? { ...me, email: e.JIRA_EMAIL, project: e.JIRA_PROJECT || "" } : null;
  } catch { return null; }
}

async function writeEnv({ email, token, cloudId, accountId, displayName, project }) {
  await mkdir(configDir, { recursive: true });
  const lines = [
    "# Generated by `jira-mcp setup`. PERSONAL — do not share.",
    "# Anyone with this token can act as you in Jira.",
    "",
    `JIRA_EMAIL=${email}`,
    `JIRA_API_TOKEN=${token}`,
    `JIRA_CLOUD_ID=${cloudId}`,
    `JIRA_ME_ACCOUNT_ID=${accountId}`,
    `JIRA_ME_NAME=${displayName}`,
    project
      ? `JIRA_PROJECT=${project}`
      : "# JIRA_PROJECT=            # no default — the agent asks which project on create",
    "",
  ];
  await writeFile(envPath, lines.join("\n"), "utf8");
  if (!isWin) { try { await chmod(envPath, 0o600); } catch { /* best effort */ } }
}

// Run the interactive wizard. Returns { email, displayName, project }.
export async function runSetup() {
  rl = createInterface({ input: process.stdin, output: process.stdout });
  try {
    let cloudId, site;
    for (let i = 0; ; i++) {
      const label = DEFAULT_SITE ? ` [${DEFAULT_SITE}]` : " (e.g. yourcompany.atlassian.net)";
      site = (await ask(`Atlassian site${label}: `, DEFAULT_SITE))
        .replace(/^https?:\/\//, "").replace(/\/.*$/, "");
      try { cloudId = await resolveCloudId(site); break; }
      catch (e) { console.log("  ✗ " + e.message + "\n"); if (i >= 2) throw new Error("Could not resolve the Atlassian site."); }
    }

    const email = await ask("Your Atlassian email: ");

    console.log(`\n  Create an API token (opening in your browser):\n    ${TOKEN_URL}\n    → "Create API token" → name it "jira-mcp" → Copy.\n`);
    openBrowser(TOKEN_URL);

    let token, me;
    for (let i = 1; ; i++) {
      token = await askHidden("Paste your Jira API token (hidden): ");
      me = await verify(cloudId, email, token);
      if (me) break;
      if (i >= 3) throw new Error("Too many failed attempts — check the email/token.");
      console.log("  ✗ Couldn't authenticate with that email + token. Try again.\n");
    }
    console.log(`  ✓ Signed in as ${me.displayName}`);

    console.log(`\n  Which Jira project do you work in most? It becomes your default.\n  Leave blank to be asked each time instead.`);
    let project = "";
    for (let i = 0; ; i++) {
      const p = (await ask("  Default project key (blank to skip): ")).toUpperCase();
      if (!p) break;
      if (await projectExists(cloudId, email, token, p)) { project = p; break; }
      console.log(`  ✗ Project "${p}" not found or not accessible.\n`);
      if (i >= 2) { console.log("  Skipping default project."); break; }
    }

    await writeEnv({ email, token, cloudId, accountId: me.accountId, displayName: me.displayName, project });
    console.log(`\n  ✓ Saved credentials to ${envPath}`);
    return { email, displayName: me.displayName, project };
  } finally {
    rl.close();
  }
}
